name: Build static site
on:
  push:
    branches: 
    - master
    - $default-branch
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo from Github
      uses: actions/checkout@v2
    - name: Update package list
      run: sudo apt update
    - name: Install gs
      run: sudo apt install ghostscript
    - name: Configure node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    - name: Clean install node package
      run: npm ci
    - name: Build node package
      run: npm run build --if-present
    - name: Run node package tests
      run: npm test
    - name: Deploy to gh-pages
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages
        folder: dist
